name: agrovida_content_pack
description: Offline bundled Agrovida content pack for FlutterFlow.
version: 0.1.1
repository: https://github.com/bakerhans/agrovida_content_pack

environment:
  sdk: ^3.9.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/agrovida_content_pack_v2.json
